export default DATA = {
    WURKERS: [
        {
            id: 0,
            name: "Joshua Beckman",
            image: "https://www.stylemotivation.com/wp-content/uploads/2019/09/plumber-main-620x496.jpg",
            description: "Hi there, I have been doing plumbing for 2 years. I have experience fixing house, restaurants, and office space. If you need a reliable and fast service I am your guy. I have the necessary equipment and an get the parts at a discount rate from my distributer.",
            skill: "Plumber",
            rating: 5,
            upvote: [0],
            downvote: [0],
            pay_rate: 50,
        },
        {
            id: 1,
            name: "Chris Bumstead",
            image: "https://barbend.com/wp-content/uploads/2021/10/Chris-Bumstead.jpg",
            "description": "Are you looking for a buff trainer to take you to the next level? Well, Im the guy for you. Knock out a couple of reps by hitting that hire button and send me a DM. Its time to build those abs",
            skill: "Trainer",
            rating: 3,
                        upvote: [0],
            downvote: [0],
            pay_rate: 50,
        },
        {
            id: 2,
            name: "Mark Zuckerburg",
            image: "https://selftaught.blog/wp-content/uploads/2019/01/MarkZuckerberg.jpg",
            "description": "I am a coder, I started a company called Facebook, but now I like to do coding in my spare time for fun.",
            skill: "Coder",
            rating: 4,
                        upvote: [0],
            downvote: [0],
            pay_rate: 50,
        },
        {
            id: 3,
            name: "Hulk Hogan",
            image: "https://blog.fantasticgardeners.co.uk/wp-content/uploads/2016/08/garden-maintenance-by-Fantastic-gardeners.jpg",
            "description": "Are you looking for a gardener with some celeb status. Thats me your famous Hulk Hogan here to provide you with exceptionally gardening skills.",
            skill: "Gardener",
            rating: 3,
                        upvote: [0],
            downvote: [0],
            pay_rate: 50,
        },
        {
            id: 4,
            name: "Ash Ketchum",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Ash_Ketchum_%285764005330%29.jpg/220px-Ash_Ketchum_%285764005330%29.jpg",
            "description": "I train pokemon, you need me. No one else has this skill",
            skill: "Pokemon Trainer",
            rating: 5,
                        upvote: [0],
            downvote: [0],
            pay_rate: 50,
        },
    ],
    PROJECTS: [
        {
            "_id": "61fe5ee76b924c82c53b7513",
            "title": "Building an Electric Car",
            "image": "https://www.forbes.com/wheels/wp-content/uploads/2020/12/Tesla-S-hero-1200px.jpg",
            "description": "I am building a fuel efficient autonomous car. This project will create cars that work with electricity only",
            "upvote": 249,
            "downvote": 44,
            "pay_rate": 50000,
            "collab": true,
            "created": 1644060362062,
            "__v": 0
        },
        {
            "_id": "61fe8574e2df5968a2899cab",
            "title": "Creating a Space Ship",
            "image": "https://cdn.geekwire.com/wp-content/uploads/2019/01/190110-starship5.jpg",
            "description": "The project will create reusable space vehicles that can transport people to low earth and geosynchronous orbit.",
            "upvote": 1239,
            "downvote": 14,
            "pay_rate": 25400000,
            "collab": true,
            "created": 1644066858245,
            "__v": 0
        },
        {
            "_id": "61fedb81219b272b68115c0a",
            "title": "Finding a Rock",
            "image": "https://www.searchenginewatch.com/wp-content/uploads/2018/10/big-rock-370x229.JPG",
            "description": "The project is about finding the hardest rock in the United States of America. I will search everywhere for it.",
            "upvote": 101,
            "downvote": 4,
            "pay_rate": 50,
            "collab": false,
            "created": 1644091775120,
            "__v": 0
        },
        {
            "_id": "61fedc28219b272b68115c0d",
            "title": "Hunting a grizzly bear",
            "image": "https://static.onecms.io/wp-content/uploads/sites/20/2019/09/grizzly-bear.jpg",
            "description": "Here I will hunt a grizzly bear. I have all the necessary equipment. I need someone to help me bring it back after I make the make the kill.",
            "upvote": 49,
            "downvote": 223,
            "pay_rate": 350,
            "collab": true,
            "created": 1644091775120,
            "__v": 0
        }
    ]
}